# This is a basic workflow to help you get started with Actions

name: 企鹅读书py

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  watch:
    types: [started]
  repository_dispatch:
        types: qqread_py

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/water008/qqread.git ~/qqread
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install requirements'
        run: |
          cd ~/qqread
          pip install -r ./requirements.txt 
      - name: '运行【企鹅读书】py' 
        run: |
          cd ~/qqread
          python3 qqread.py 
        env:
            QQREADHEADERS: ${{ secrets.QQREAD_HEADER }}
            QQREADTIMEURL: ${{ secrets.QQREAD_TIMEURL }}
            QQREADTIMEHEADERS: ${{ secrets.QQREAD_TIMEHD }}
            NOTIFYTYPE: ${{ secrets.NOTIFYTYPE }}
            NOTIFYCFG: ${{ secrets.NOTIFYCFG }}
            SCKEY: ${{ secrets.SCKEY }}
            BARK: ${{ secrets.BARK }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
